### ISSUE TITLE
How I can use Esp Exception Decoder on PlatformIO?

### ISSUE THREAD

**Issue by lucasromeiro** [platformio/platform-espressif8266#126] opened 2019-02-20 18:45 UTC
Its don't work...
How I can decoder the exceptions?

https://github.com/me-no-dev/EspExceptionDecoder

**Comment by ivankravets** [comment] 2019-02-23 22:35
Duplicate of https://github.com/platformio/platform-espressif8266/issues/31

**Closed by ivankravets** 2019-02-23 22:35 UTC
