### ISSUE TITLE
ESP8266 SDK22x_191024 does not work reliable with old Xtensa Build chain

### ISSUE THREAD

**Issue by Jason2866** [platformio/platform-espressif8266#180] opened 2019-11-08 12:27 UTC
- [x] **PlatformIO Core**.
      
Please update Xtensa build chain for ESP8266 to latest 2.5.x version for feature/stage.
The newer Non Os SDK versions 2.2.2 from 191024 and 191105 does NOT work
reliable with the the used build chain.

When compiling Tasmota with the Xtensa Build Chain 2.4.x there are wifi reconnects.
Using Xtensa Build chain 2.5.0.4 solves this issues.

I have done a custom setup (dirty hack for windows) to use the 2.5.x version.
https://github.com/Jason2866/platform-espressif8266.git#SDK22x_191105
   

------------------------------------------------------------------

### Configuration

**Operating system**: Windows 10 pro 

**PlatformIO Version** (`platformio --version`): Latest dev version

### Description of problem
Compiled firmware is unreliable.

#### Steps to Reproduce
Compile Tasmota with old Xtensa Build chain.
Issue solving:
Compile Tasmota with new (in Arduino IDE default) build chain

**The content of `platformio.ini`:**

[platformio.zip](https://github.com/platformio/platformio-core/files/3824513/platformio.zip)

**Source file to reproduce issue:**
https://github.com/arendst/Tasmota

**Comment by Jason2866** [comment] 2019-11-08 12:41
Arduino Core 2.6.0 will be released this week :-)
https://github.com/esp8266/Arduino/pull/6724#issuecomment-551610434

**Comment by TD-er** [comment] 2019-11-08 23:49
> Arduino Core 2.6.0 will be released this week :-)
> [esp8266/Arduino#6724 (comment)](https://github.com/esp8266/Arduino/pull/6724#issuecomment-551610434)

It has been released :)

**Comment by ascillato** [comment] 2019-11-09 04:05
@ivankravets 

Hi,

Core 2.6.0 has been just released but requires to update toolchain to 2.5.0-4

Using previous toolchain (2.4.x) produces firmwares that have wifi disconnections for ESP8266 devices.

Thanks.

**Comment by Jason2866** [comment] 2019-11-14 16:45
Core 2.6.1 is released
@TD-er  You can use with 
`platform                  = https://github.com/Jason2866/platform-espressif8266.git#core_2_6_1`

**Comment by dirkmueller** [comment] 2019-11-15 06:25
Duplicate of #167

**Comment by arendst** [comment] 2019-11-17 16:29
Hi @ivankravets pls give this priority as I would like to release Tasmota one of these days using a stable platformio environment

Thx in advance.

**Comment by ivankravets** [comment] 2019-11-17 16:34
Could someone summarize what should be done from our side? We have support for Arduino and native SDK. Is the new compiler compatible with SDK version which we support? Or, the new toolchain should be used for new Arduino?

**Comment by Jason2866** [comment] 2019-11-17 19:02
@ivankravets  **Release core 2.6.1 as platformio-espressif8266 package with Xtensa build chain 2.5.0.4**
The new SDK version SDK22x_191105 does solve many issues but requires Xtensa build chain 2.5.0.4.
If the older build chain is used it generates wifi issues

**Comment by ivankravets** [comment] 2019-11-17 19:46
@Jason2866 I mean "framework-esp8266-rtos-sdk" and "framework-esp8266-nonos-sdk". Are they compatible with this new toolchain?

**Comment by Jason2866** [comment] 2019-11-17 20:23
@ivankravets  tbh, i dont know. Never used framework-esp8266-rtos-sdk
Arduino ESP8266 is only nonos-sdk.

**Comment by dirkmueller** [comment] 2019-11-17 20:24
@ivankravets as far as I can see it is just bugfixes, should be compatible with anything

**Comment by Jason2866** [comment] 2019-11-23 17:56
@ivankravets  any news? Maybe a release date? ;-)

**Closed** 2019-11-25 11:28 UTC

**Comment by Jason2866** [comment] 2019-11-25 11:49
@valeros  Thx, but it does still install old Xtensa toolchain.
![image](https://user-images.githubusercontent.com/24528715/69538182-03ac2580-0f82-11ea-9186-62345a2a3177.png)

**Comment by valeros** [comment] 2019-11-25 11:57
`2.40802.191122` it's our internal version of `2.5.0-4`

**Comment by Jason2866** [comment] 2019-11-25 11:59
Ahh thx!

**Comment by arendst** [comment] 2019-11-25 15:23
Thx too.

**Comment by TD-er** [comment] 2019-11-25 16:18
Thanks three :)

**Comment by andrethomas** [comment] 2019-11-25 17:55
And four, much appreciated :)
