### ISSUE TITLE
cannot use OTA using esp8266-rtos-sdk framework 

### ISSUE THREAD

**Issue by Mr-Techtron** [platformio/platform-espressif8266#106] opened 2018-11-04 03:19 UTC
8:47:49.544>  ets Jan  8 2013,rst cause:2, boot mode:(3,7)
8:47:49.544> 
8:47:49.544> 
8:47:49.544> 
8:47:49.544> load 0x40100000, len 2592, room 16 
8:47:49.544> 
8:47:49.544> tail 0
8:47:49.544> 
8:47:49.544> chksum 0xf3
8:47:49.544> 
8:47:49.544> load 0x3ffe8000, len 764, room 8 
8:47:49.544> 
8:47:49.544> tail 4
8:47:49.544> 
8:47:49.544> chksum 0x92
8:47:49.544> 
8:47:49.544> load 0x3ffe82fc, len 676, room 4 
8:47:49.544> 
8:47:49.544> tail 0
8:47:49.544> 
8:47:49.544> chksum 0x22
8:47:49.544> 
8:47:49.544> csum 0x22
8:47:49.544> 
8:47:49.544> 
8:47:49.544> 
8:47:49.544> 2nd boot version : 1.7(5d6f877)
8:47:49.544> 
8:47:49.544> SPI Speed : 40MHz
8:47:49.544> 
8:47:49.544> SPI Mode : QIO
8:47:49.544> 
8:47:49.544> SPI Flash Size & Map: 32Mbit(512KB+512KB)
8:47:49.544> 
8:47:49.544> jump to run user2 @ 81000
8:47:49.544> 
8:47:49.544> 
8:47:49.544> 
8:47:49.544> error magic!
8:47:49.544> 
8:47:49.544> backup boot failed.
8:47:49.544> 
8:47:49.544> 
8:47:49.544> 
8:47:49.544> user code done

I'm trying to do OTA using the esp8266-rtos-sdk framework but I can't find any documentation to do it. I can only find documentation for arduino framework. Can somebody guide me here to create user1.bin using platformio and esp8266-rtos-sdk framework?

**Comment by ivankravets** [comment] 2019-03-04 11:33
Duplicate of https://github.com/platformio/platform-espressif8266/issues/62

**Closed by ivankravets** 2019-03-04 11:33 UTC
